### ISSUE TITLE
Weds 20-05-15 Pub Social

### ISSUE THREAD

**Issue by olorton** [phpoxford/phpoxford.github.io#1]
Like last time let's meetup in the Cape if that works for everyone else?

**Comment by olorton** [comment]
@liquorvicar Has suggested that we should not always meetup in the same weekday every time. Since we agreed this date at the last meeting I think that we should stick to it, but I'll move the next one to a different day.

**Comment by liquorvicar** [comment]
@olorton Works for me.

**Comment by liquorvicar** [comment]
FWIW the reasoning behind changing the day is that some people can't make certain days of the week (e.g. a colleague of mine who would like to come but has childcare issues on a Weds). Given that whatever day of the week we pick there will always be somebody who has an issue with that day, it might be a good idea to rotate which day of the week the meeting is on each month (maybe not around all 7 days but pick 2, 3 or 4 days to use).

**Comment by olorton** [comment]
@liquorvicar I completely agree, after our conversation at the Ansible meetup the thursday became difficult for me. I'm going to publish this date on twitter now and raise a new issue for the meetup following this.

**Comment by liquorvicar** [comment]
@olorton I have submitted the May meet to php.net...

**Comment by liquorvicar** [comment]
Think I've got 2 or 3 coming from my current place and maybe a couple from my last place too.
