### ISSUE TITLE
Thurs 25-06-15 Pub Meetup

### ISSUE THREAD

**Issue by olorton** [phpoxford/phpoxford.github.io#2]
We're going to try a thursday, @liquorvicar can you ping your workmates?

**Comment by olorton** [comment]
It looks like PHPBerks have a meetup every third weds of the month, so I suggest that I re-visit exactly when it is during the month that we meet. https://twitter.com/choult/status/596052741979508736

**Comment by liquorvicar** [comment]
Thurs is generally good for me as I'm usually off on Fridays ;-)
One of my workmates is coming this month, one of the others can only make Tuesday evenings so we shouldn't plan dates round him.
How about something like alternating between 2nd Tues and 2nd Thurs of month? Or are there other meets you're trying to avoid?

**Comment by olorton** [comment]
Yup, confirmed. I have just announced it on twitter
https://twitter.com/phpoxford/status/605102559259422720
http://phpoxford.eventbrite.co.uk

Right now I'm not sure what the state of other meetups is. I'll look into before the next meetup. 

I do really like weds/thurs, tues doesn't suit me quite as well, but I think we should just randomly try for one of those 3 days each time. If we have speakers at events, or are targeting someone specifically, then we should offer a choice to them. Let's see how this works out, we can always be more rigid if we need to.
